#!/usr/bin/env bash

# NOTE: This file should be placed in the same directory as agda
BIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
SHR_DIR=$(realpath $BIN_DIR/../share)
ETC_DIR=$(realpath $BIN_DIR/../etc)
OPT_DIR=$(realpath $BIN_DIR/../opt)
DATA_DIR=$SHR_DIR/agda/data
LIBS_DIR=$SHR_DIR/agda/libs
OPT_LIBS_DIR=$OPT_DIR/agda/libs
APP_DIR=$ETC_DIR/agda

# File paths
LIBRARIES_FILE_PATH=$APP_DIR/libraries
DEFAULTS_FILE_PATH=$APP_DIR/defaults
